# Generated by Django 3.1.7 on 2023-11-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0003_productrecords_supplier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrecords',
            old_name='supplier_name',
            new_name='owner',
        ),
    ]
