# Generated by Django 3.1.7 on 2023-11-06 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0004_auto_20231106_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecords',
            name='owner',
        ),
    ]
