# Generated by Django 3.1.7 on 2023-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0005_remove_productrecords_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBumMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(db_column='supplier_name', max_length=64)),
                ('bum', models.CharField(db_column='bum', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Supplier Bum Mapping',
                'db_table': 'supplier_bum_mapping',
            },
        ),
    ]
