# Generated by Django 3.1.7 on 2023-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0006_supplierbummapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierbummapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplierbummapping',
            name='supplier_name',
            field=models.CharField(db_column='supplier_name', max_length=64, primary_key=True, serialize=False),
        ),
    ]
