# Generated by Django 3.1.7 on 2023-12-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0007_auto_20231114_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundles',
            fields=[
                ('bundle_code', models.CharField(db_column='bundle_code', max_length=64, primary_key=True, serialize=False)),
                ('components', models.CharField(db_column='components', max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Bundles',
                'db_table': 'bundles',
            },
        ),
    ]
