# Generated by Django 3.1.7 on 2024-04-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0008_bundles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierbummapping',
            old_name='bum',
            new_name='business_unit_manager',
        ),
    ]
