# Generated by Django 3.1.7 on 2024-06-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0009_auto_20240418_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecords',
            name='delete_flag',
            field=models.BooleanField(blank=True, null=True, verbose_name='Discontinued'),
        ),
    ]
