# Generated by Django 3.1.7 on 2024-07-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0010_auto_20240605_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecords',
            name='is_in_website',
            field=models.BooleanField(blank=True, null=True, verbose_name='Update price only'),
        ),
    ]
