# Generated by Django 3.1.7 on 2024-07-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0011_auto_20240724_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrecords',
            old_name='is_in_website',
            new_name='price_change_only',
        ),
    ]
