# Generated by Django 3.1.7 on 2024-07-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0012_auto_20240724_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrecords',
            old_name='price_change_only',
            new_name='price_update_only',
        ),
    ]
