# Generated by Django 5.0.6 on 2025-01-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0015_auto_20241022_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPricingRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MIN_SELL_PRICE_CURRENCY_ID', models.IntegerField()),
                ('NETT_PRICE_LOWER_LEVEL', models.FloatField()),
                ('NETT_PRICE_UPPER_LEVEL', models.FloatField()),
                ('LEVEL_MULTIPLER', models.FloatField()),
            ],
        ),
    ]
