# Generated by Django 5.0.6 on 2025-01-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0016_supplierpricingrules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierPricingRules',
            new_name='DefaultSupplierPricingRules',
        ),
    ]
