# Generated by Django 5.0.6 on 2025-01-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0017_rename_supplierpricingrules_defaultsupplierpricingrules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultsupplierpricingrules',
            options={'managed': False},
        ),
    ]
