# Generated by Django 5.0.6 on 2025-01-24 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0018_alter_defaultsupplierpricingrules_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='defaultsupplierpricingrules',
            table='defaultsupplierpricingrules',
        ),
    ]
