# Generated by Django 5.0.6 on 2025-01-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0019_alter_defaultsupplierpricingrules_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataowners',
            name='delete_flag',
            field=models.PositiveIntegerField(db_column='delete_flag', default=0),
        ),
    ]
