# Generated by Django 5.0.6 on 2025-03-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myDatabase', '0020_dataowners_delete_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrecordstech',
            old_name='selection_marker',
            new_name='anticoagulant',
        ),
    ]
