# Generated by Django 3.1.7 on 2024-07-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_livecurrencyrate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecurrencyrate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
