# Generated by Django 5.0.6 on 2025-01-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20240724_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livecurrencyrate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
